#!/usr/bin/bash

getTotalBatteryPercentage() {
	path_ac="/sys/class/power_supply/AC"
	path_battery_0="/sys/class/power_supply/BAT0"
	path_battery_1="/sys/class/power_supply/BAT1"

	battery_level_0=0
	battery_level_1=0
	battery_max_0=0
	battery_max_1=0

	if [ -f "$path_battery_0/energy_now" ]; then
    battery_level_0=$(cat "$path_battery_0/energy_now")
	fi

	if [ -f "$path_battery_0/energy_full" ]; then
		battery_max_0=$(cat "$path_battery_0/energy_full")
	fi

	if [ -f "$path_battery_1/energy_now" ]; then
		battery_level_1=$(cat "$path_battery_1/energy_now")
	fi

	if [ -f "$path_battery_1/energy_full" ]; then
		battery_max_1=$(cat "$path_battery_1/energy_full")
	fi

	battery_level=$(("$battery_level_0 + $battery_level_1"))
	battery_max=$(("$battery_max_0 + $battery_max_1"))

	battery_percent=$(("$battery_level * 100"))
	battery_percent=$(("$battery_percent / $battery_max"))
	echo $battery_percent
}

getBatteryCharginStatus() {
	if $(acpi -b | grep --quiet Discharging)
	then
		echo "Discharging";
	else # acpi can give Unknown or Charging if charging, https://unix.stackexchange.com/questions/203741/lenovo-t440s-battery-status-unknown-but-charging
		echo "Charging";
	fi
}

status=$(getBatteryCharginStatus)
echo $status
battery_level=$(getTotalBatteryPercentage)
echo $battery_level

if [[ $status = 'Discharging' && $battery_level -le 10 ]]
then
	notify-send -i gnome-warning "Battery low" "Save your work or plug your AC adapter!" -u critical -t 0
fi

exit 0;
