#!/usr/bin/bash
path=(~/Dropbox/Pictures/Wallpapers)

image() {
	find $path | shuf -n1
}

WALLPAPER=$(image)

while [ -d "$WALLPAPER" ]
do
	WALLPAPER=$(image)
done

# WALLPAPER2=$(printf "%s\n" "${files[RANDOM % ${#files[@]}]}")

cp "$WALLPAPER" ~/.config/wall.png
cp "$WALLPAPER" /usr/share/backgrounds/wall.png

if [ "$XDG_SESSION_TYPE" = "x11" ]
then
	feh --bg-fill ~/.config/wall.png
elif [ "$XDG_SESSION_DESKTOP" = "gnome" ]
then
  gsettings set "org.gnome.desktop.background" picture-uri "file:///$WALLPAPER"
else
	swaymsg output "*" background ~/.config/wall.png fill
fi
# notify-send -i "$WALLPAPER" "Wallpaper changed"

# Use for multiple screens
# feh -B white --bg-fill $WALLPAPER --bg-fill $WALLPAPER2
