#!/usr/bin/bash
path=(~/Dropbox/Pictures/Wallpapers)

image() {
	find $path | shuf -n1
}

WALLPAPER=$(image)

while [ -d "$WALLPAPER" ]
do
	WALLPAPER=$(image)
done

# WALLPAPER2=$(printf "%s\n" "${files[RANDOM % ${#files[@]}]}")

cp "$WALLPAPER" ~/.config/wall.png && feh --bg-fill ~/.config/wall.png
# notify-send -i "$WALLPAPER" "Wallpaper changed"

# Use for multiple screens
# feh -B white --bg-fill $WALLPAPER --bg-fill $WALLPAPER2
