#!/bin/sh

swaymsg output eDP-1 disable
swaymsg output eDP-1 dpms off
swaymsg output DP-4 enable scale 1
swaymsg output DP-4 pos 0 360 res 1920x1080
swaymsg output DP-3 enable scale 1
swaymsg output DP-3 pos 1920 0 res 2560x1440
