#!/bin/sh

KEYBOARD="$KEYBOARD"
CURRENT=$(
swaymsg -t get_inputs |
  jq -r --arg KEYBOARD "$KEYBOARD" '
  .[]
  | select(.xkb_active_layout_name == "Greek" and .identifier == $KEYBOARD)'
)

ENGLISH=$"English (US)"

if [ "$CURRENT" ]; then
  echo "Equals greek"
  swaymsg "input * xkb_switch_layout 0"
  $1
  echo "exit: $?"
  swaymsg "input * xkb_switch_layout 1"
  echo "Change to greek"
else
  echo "English"
  $1
fi

exit 0
