#!/bin/sh
CURRENT=$(swaymsg -t get_inputs | jq '.[4].xkb_active_layout_name')
ENGLISH=$"English (US)"

if [ "$CURRENT" == "\"Greek\"" ]; then
	echo "Equals greek"
	swaymsg "input * xkb_switch_layout 0"
	$1
	swaymsg "input * xkb_switch_layout 1"
	exit 0
else
	echo "English"
	$1
	exit 0
fi
