#!/bin/sh

# This is the ffmpeg command that the screencast shortcut in i3 will run.

# Picks a file name for the output file based on availability:

filename="$HOME/Videos/screencast-$(date +%Y-%m-%d_%H-%M-%S).mp4"

wf-recorder -f "$filename" -o "$1"
