#!/bin/sh
MINUTE=1000

getIcon() {
	volume="$1"
	if [ "$volume" -gt 75 ]; then
		icon="/usr/share/icons/Papirus/48x48/status/notification-audio-volume-high.svg"
	elif [ "$volume" -gt 25 ]; then
		icon="/usr/share/icons/Papirus/48x48/status/notification-audio-volume-medium.svg"
	else
		icon="/usr/share/icons/Papirus/48x48/status/notification-audio-volume-low.svg"
	fi

	echo "$icon"
}

alert() {
	volume=$(pamixer --get-volume)
  mediaStatus=$(! pacmd list-sink-inputs | grep -c "state: RUNNING")

  if [ $volume -le 99 ] && [ $mediaStatus == 0 ]; then
     canberra-gtk-play -i audio-volume-change -d "changeVolume"
  fi

  bar=$(get-progress-string 10 "<b>  </b>" "<b>  </b>" "$volume")

	icon=$(getIcon "$volume")

	notify-send.sh "$volume" --icon="$icon" --replace-file=/tmp/volumenotification "$bar" -t "$MINUTE"
}

toggle() {
	amixer -q -D pulse sset Master toggle

	if pamixer --get-mute; then
		icon="/usr/share/icons/Papirus/48x48/status/notification-audio-volume-muted.svg"
	else
		icon="/usr/share/icons/Papirus/48x48/status/notification-audio-volume-high.svg"
	fi

	notify-send.sh --icon="$icon" " " --replace-file=/tmp/volumenotification -t "$MINUTE"
}

case "$1" in
	--decrease)
	amixer -q -D pulse sset Master "$2"%-
	alert
	;;
	--increase)
	amixer -q -D pulse sset Master "$2"%+
	alert
	;;
	--toggle)
	toggle
	;;
	*)
	echo "Wrong argument"
	;;
esac
