#!/bin/sh
MINUTE=1000

getIcon() {
	volume="$1"
    if [ "$volume" -gt 80 ]; then
        icon="/usr/share/icons/Papirus/48x48/status/notification-microphone-sensitivity-high.svg"
    elif [ "$volume" -gt 50 ]; then
        icon="/usr/share/icons/Papirus/48x48/status/notification-microphone-sensitivity-medium.svg"
    else
        icon="/usr/share/icons/Papirus/48x48/status/notification-microphone-sensitivity-low.svg"
    fi

	echo "$icon"
}

alert() {
	volume=$(pamixer --default-source --get-volume)
	# bar=$(seq -s "─" "$(($volume / 6))" | sed 's/[0-9]//g')
  bar=$(get-progress-string 10 "<b>  </b>" "<b>  </b>" "$volume")

	icon=$(getIcon "$volume")

	notify-send.sh "$volume" --icon="$icon" --replace-file=/tmp/volumenotification "$bar" -t "$MINUTE"
}

toggle() {
	amixer set Capture toggle

	if pamixer --default-source --get-mute; then
			icon="/usr/share/icons/Papirus/48x48/status/notification-microphone-sensitivity-muted.svg"
		else
			icon="/usr/share/icons/Papirus/48x48/status/notification-microphone-sensitivity-high.svg"
		fi

	notify-send.sh --icon="$icon" " " --replace-file=/tmp/volumenotification -t "$MINUTE"
}

case "$1" in
	--decrease)
	amixer set Capture "$2"%-
	alert
	;;
	--increase)
	amixer set Capture "$2"%+
	alert
	;;
	--toggle)
	toggle
	;;
	*)
	echo "Wrong argument"
	;;
esac
