#!/bin/bash

CURRENT_WINDOW=$(xdotool getwindowfocus)

xdotool windowfocus "$CURRENT_WINDOW"
opt=$(rofi-emoji | rofi -width 35 -lines 16 -dmenu -i -p ' 😀')
return_code=$?

if [ $return_code -ne 1 ]
then
  smiley=$(echo $opt | cut -d' ' -f1)
  echo "$smiley"
  echo -n "$smiley" | xsel --clipboard
	xdotool key --clearmodifiers Shift+Insert; wait
  exit 0
fi
