#!/bin/sh

opt=$(rofi-emoji | rofi -width 35 -lines 16 -dmenu -i -p ' 😀')
return_code=$?

if [ $return_code -ne 1 ]
then
  smiley=$(echo $opt | cut -d' ' -f1)
  # echo -n "$smiley" | xsel --clipboard --input
  echo -n "$smiley" | xclip -selection clipboard -in
  xdotool key Shift+Insert
  exit 0
fi
