#!/bin/sh
FILENAME="$HOME/Pictures/screenshots/screenshot-$(date +%Y-%m-%d-%H-%M-%S).png"

SCREEN=$(swaymsg -t get_outputs | jq -r '.[] | select(.focused) | .name')

blurImage() {
	grim -o "$SCREEN" "$FILENAME"

	convert "$FILENAME" -scale 10% -blur 0x1 -resize 1000% ~/.config/blur.png

	# convert "$FILENAME" -scale 2.5% -resize 4000% ~/.config/blur.png
}

xlock() {
	i3lock --blur=1 --clock --indicator --insidecolor=232c31ff --ringcolor=9ea7a6ff --line-uses-inside --keyhlcolor=2a5491ff --bshlcolor=a03b1eff --insidevercolor=232c31ff --insidewrongcolor=a03b1eff --ringvercolor=9ea7a6ff --ringwrongcolor=3f4944ff --separatorcolor=2a5491ff --verifcolor=ffffffff --wrongcolor=232c31ff --timecolor=ffffffff --datecolor=ffffffff
}

if [ "$XDG_SESSION_TYPE" = "x11" ]
then
	CURRENT=$(xkblayout-state print %s)

	if [ "$CURRENT" != "us" ]
	then
		xkb-switch -n
	fi

	xlock
else
	# blurImage
	swaylock
fi
