#!/usr/bin/env bash
# shellcheck disable=SC2016

minute() {
  echo $(($1*60))
}

# Run xidlehook
xidlehook \
  --not-when-fullscreen \
  --not-when-audio \
  --timer normal 2 \
		'echo $(light -G) > /tmp/screenBrightnessValue && light -S 5' \
    '[ -f /tmp/screenBrightnessValue ] && light -S $(cat /tmp/screenBrightnessValue) && rm /tmp/screenBrightnessValue' \
    --timer primary 3 \
    ' ! pgrep i3lock && [ -f /tmp/screenBrightnessValue ] && light -S $(cat /tmp/screenBrightnessValue) && rm /tmp/screenBrightnessValue && custom-lock' \
    '' \
    --timer normal "$(minute 30)" \
    'systemctl suspend' \
    ''
