#!/bin/sh

FILENAME="$HOME/Pictures/screenshots/screenshot-$(date +%Y-%m-%d-%H-%M-%S).png"

maim -i $(xdotool getactivewindow) $FILENAME
# maim -i $(xdotool getactivewindow) | convert - \( +clone -background black -shadow 80x3+5+5 \) +swap -background none -layers merge +repage $FILENAME

notify-send -i "$FILENAME" "Saved focused window to clipboard and under ~/Pictures/screenshots/"
xclip -selection clipboard -t image/png -i $FILENAME
