#!/bin/sh

FILENAME="$HOME/Pictures/screenshots/imgur-$(date +%Y-%m-%d-%H-%M-%S).png"

maim -s $FILENAME; imgur $FILENAME
# maim -s | convert - \( +clone -background black -shadow 80x3+5+5 \) +swap -background none -layers merge +repage $FILENAME; imgur $FILENAME

