#!/bin/sh
set -e

WALLPAPER=$1
MODE=$2

x11Set() {
  cp "$WALLPAPER" ~/.config/wall.png
  feh --bg-fill ~/.config/wall.png
}

wlSet() {
  cp "$WALLPAPER" ~/.config/wall.png
	swaymsg output "*" background "$WALLPAPER" fill
}

action() {
	if [ "$XDG_SESSION_TYPE" = "wayland" ]
	then
		$1
	else
		$2
	fi
}

case "$MODE" in
  fill)
			action wlSet x11Set
			notify-send -i "$WALLPAPER" "Wallpaper changed"
		;;
	*)
		echo "💩 Invalid option"
		;;
esac
