#!/bin/sh
set -e

FILENAME="$HOME/Pictures/screenshots/screenshot-$(date +%Y-%m-%d-%H-%M-%S).png"
INPUT=$1

wlActiveScreen() {
	SCREEN=$(swaymsg -t get_outputs | jq -r '.[] | select(.focused) | .name')

	grim -o "$SCREEN" "$FILENAME"
	wl-copy < "$FILENAME"
}

wlActiveWindow() {
  WINDOW=$(swaymsg -t get_tree | jq -r 'recurse(.nodes[]?, .floating_nodes[]?) | select(.focused)')
  GEOM=$(echo "$WINDOW" | jq -r '.rect | "\(.x),\(.y) \(.width)x\(.height)"')

	grim -g "$GEOM" "$FILENAME"
	wl-copy < "$FILENAME"
}

wlRegion() {
	grim -g "$(slurp)" "$FILENAME"
	wl-copy < "$FILENAME"
}

x11ActiveScreen() {
	SCREEN=$(get-active-monitor)

	maim -g "$SCREEN" "$FILENAME"
	xclip -selection clipboard -t image/png -i "$FILENAME"
}

x11ActiveWindow() {
	maim -i "$(xdotool getactivewindow)" "$FILENAME"
	xclip -selection clipboard -t image/png -i "$FILENAME"
}

x11Region() {
	maim -s "$FILENAME"
	xclip -selection clipboard -t image/png -i "$FILENAME"
}

action() {
	if [ "$XDG_SESSION_TYPE" = "wayland" ]
	then
		$1
	else
		$2
	fi
}

case "$INPUT" in
	imgur)
			action wlRegion x11Region
			imgur "$FILENAME"
		;;
	imgur-window)
			action wlActiveWindow x11ActiveWindow
			imgur "$FILENAME"
		;;
	imgur-screen)
			action wlActiveScreen x11ActiveScreen
			imgur "$FILENAME"
		;;
	screen)
			action wlActiveScreen x11ActiveScreen
			notify-send -i "$FILENAME" "Saved active screen to clipboard and under ~/Pictures/screenshots/"
		;;
	window)
			action wlActiveWindow x11ActiveWindow
			notify-send -i "$FILENAME" "Saved focused window to clipboard and under ~/Pictures/screenshots/"
		;;
	region)
			action wlRegion x11Region
			notify-send -i "$FILENAME" "Image copied to clipboard and under ~/Pictures/screenshots/"
		;;
	*)
		echo "💩 Invalid option"
		;;
esac
