#!/bin/bash
# From https://github.com/x70b1/polybar-scripts/blob/master/polybar-scripts/openweathermap-simple/openweathermap-simple.sh
source ~/.tokens

get_icon() {
	case $1 in
		01d) icon="";;
		01n) icon="";;
		02d) icon="";;
		02n) icon="";;
		03*) icon="";;
		04*) icon="";;
		09d) icon="";;
		09n) icon="";;
		10d) icon="";;
		10n) icon="";;
		11d) icon="";;
		11n) icon="";;
		13d) icon="";;
		13n) icon="";;
		50d) icon="";;
		50n) icon="";;
		*) icon="";
	esac

	echo $icon
}

KEY="$WEATHER_TOKEN"
CITY="263824"
UNITS="metric"

if [ -n "$CITY" ]; then
	weather=$(curl -sf "http://api.openweathermap.org/data/2.5/weather?APPID=$KEY&id=$CITY&units=$UNITS")
else
	location=$(curl -sf https://location.services.mozilla.com/v1/geolocate?key=geoclue)

	if [ -n "$location" ]; then
		location_lat="$(echo "$location" | jq '.location.lat')"
		location_lon="$(echo "$location" | jq '.location.lng')"

		weather=$(curl -sf "http://api.openweathermap.org/data/2.5/weather?appid=$KEY&lat=$location_lat&lon=$location_lon&units=$UNITS")
	fi
fi

if [ -n "$weather" ]; then
	weather_icon=$(echo "$weather" | jq -r ".weather[].icon")

	get_icon "$weather_icon"
fi

