#!/bin/sh
xrandr --output eDP1 --mode 1920x1080 --pos 2240x1440 --rotate normal --output DP1 --off --output DP1-1 --off --output DP1-8 --off --output DP2 --off --output HDMI1 --off --output HDMI2 --off --output VIRTUAL1 --off

