#!/bin/sh
xrandr --output DVI-I-0 --off --output DP-1.8 --primary --mode 2560x1440 --pos 0x0 --rotate normal --output DP-1.1 --off --output DVI-I-1 --off --output HDMI-0 --off --output DP-0 --off --output DVI-D-0 --off --output DP-1 --off
