#!/bin/sh
xrandr --output eDP1 --off --output DP1 --off --output DP1-1 --off --output DP1-8 --primary --mode 2560x1440 --pos 0x0 --rotate normal --output DP2 --off --output HDMI1 --off --output HDMI2 --off --output VIRTUAL1 --off
