#!/bin/sh
# xrandr --output eDP1 --mode 1920x1080 --pos 320x1440 --rotate normal --output DP1 --primary --mode 2560x1440 --pos 0x0 --rotate normal --output DP2 --off --output HDMI1 --off --output HDMI2 --off --output VIRTUAL1 --off

# xrandr --output eDP1 --mode 1920x1080 --pos 1400x1440 --rotate normal --output DP1 --off --output DP1-1 --mode 1920x1080 --pos 0x0 --rotate left --output DP1-8 --primary --mode 2560x1440 --pos 1080x0 --rotate normal --output DP2 --off --output HDMI1 --off --output HDMI2 --off --output VIRTUAL1 --off

xrandr --output eDP1 --mode 1920x1080 --pos 2240x1440 --rotate normal --output DP1 --off --output DP1-1 --mode 1920x1080 --pos 0x0 --rotate normal --output DP1-8 --primary --mode 2560x1440 --pos 1920x0 --rotate normal --output DP2 --off --output HDMI1 --off --output HDMI2 --off --output VIRTUAL1 --off
